apiVersion: v1
kind: Namespace
metadata:
  name: nginx-autopilot-spot
  labels:
    environment: poc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-autopilot-spot
  namespace: nginx-autopilot-spot
spec:
  selector:
    matchLabels:
      app: nginx-autopilot-spot
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-autopilot-spot
    spec:
      containers:
        - name: nginx-autopilot-spot
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "250m"
              memory: "64Mi"
      nodeSelector: # This is not required if the label has added to namespace level
        cloud.google.com/compute-class: "autopilot-spot"
