apiVersion: v1
kind: Namespace
metadata:
  name: nginx-normal
  labels:
    environment: poc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-normal
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "200m"
              memory: "64Mi"
